### ISSUE TITLE
config.cc:457:29: warning: catching polymorphic type 'class string_format::ParseError' by value [-Wcatch-value=]

### ISSUE THREAD

**Issue by dcb314** [jwilk/pdf2djvu#122]
Source code is

    catch (string_format::ParseError)

Maybe better code

    catch (const string_format::ParseError &)

**Comment by jwilk** [comment]
Thanks for the bug report.
Fixed in 7e836d16a2cdc1fb54b6211f489eefef67695e0e.

**Comment by jwilk** [comment]
Fixed in 0.9.6.
