### ISSUE TITLE
Some tests failed: PDF syntax warning: EOF while reading header (continuing anyway)

### ISSUE THREAD

**Issue by LazyKent** [jwilk/pdf2djvu#130]
Building pdf2djvu-0.9.9 in openSUSE Tumbleweed 20180425 x86_64.
```
...
FAIL: test-empty-outline.test.test
...
FAIL: test-no-meta.test.test
...
FAIL: test-xmp-recreate.test.test_no_verbatim
...
FAIL: test-xmp-recreate.test.test_verbatim
...
```
The build log attached.

[build.log.gz](https://github.com/jwilk/pdf2djvu/files/1964660/build.log.gz)

**Comment by jwilk** [comment]
> ```
> ======================================================================
> FAIL: test-empty-outline.test.test
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
>     self.test(*self.arg)
>   File "/home/abuild/rpmbuild/BUILD/pdf2djvu-0.9.9/tests/test-empty-outline.py", line 25, in test
>     self.pdf2djvu().assert_()
>   File "/home/abuild/rpmbuild/BUILD/pdf2djvu-0.9.9/tests/tools.py", line 143, in assert_
>     assert_multi_line_equal(self.stderr, stderr)
> AssertionError: 'PDF syntax warning: EOF while reading header (continuing anyway)\nPDF syntax wa [truncated]... != ''
> - PDF syntax warning: EOF while reading header (continuing anyway)
> - PDF syntax warning: EOF while reading header (continuing anyway)
> - PDF syntax warning: EOF while reading header (continuing anyway)
> ```

This is manifestation of a bug in Poppler. Please cherry-pick [e491e935ea35](https://cgit.freedesktop.org/poppler/poppler/patch/?id=e491e935ea355d48519cf0a14e4b060655850675) or upgrade to Poppler 0.64.

I don't plan to implement work-around for this, but I'll keep this bug open for a few weeks to deter other packagers from filing duplicates.

**Comment by jwilk** [comment]
Hopefully everyone upgraded Poppler by now.
Let's close this bug.
