### ISSUE TITLE
Windows: cannot open files with non-ASCII characters in names

### ISSUE THREAD

**Issue by DJVU-SPEC** [jwilk/pdf2djvu#138]
pdf2djvu 0.9.8
![oblom-s_p2d 0 9 8_2019-06-07](https://user-images.githubusercontent.com/51449525/59099571-a5e13e00-894d-11e9-98d2-527e0dfa3bf2.jpg)

**Comment by DJVU-SPEC** [comment]
Please test work of pdf2djvu with other codepages!!!
Here test suit for win32.
Error from 0.9.8! There was "Out of memory"
Now - can't read at all!
![oblom-s_p2d 0 9 12_2019-06-06](https://user-images.githubusercontent.com/51449525/59039702-7f64c980-889f-11e9-8242-26ca90aa51b7.jpg)
[УКР_2014 1.zip](https://github.com/jwilk/pdf2djvu/files/3261971/_2014.1.zip)

**Comment by jwilk** [comment]
Thanks for the bug report.

I think [a6dd3f957f59](https://cgit.freedesktop.org/poppler/poppler/commit/?id=a6dd3f957f5979fa34a05ba963862de7d0d9df61) in Poppler 0.62 broke it:
Poppler now expects filenames encoded as UTF-8, but pdf2djvu uses locale encoding.

Should be easy to fix.

**Comment by DJVU-SPEC** [comment]
Jakub, please, use test suit with non ascii!

**Comment by jwilk** [comment]
Fixed in [0.9.13](https://groups.io/g/pdf2djvu/message/121).
