### ISSUE TITLE
win32 release

### ISSUE THREAD

**Issue by GitHubRulesOK** [jwilk/pdf2djvu#140]
current win 32 on homepage and here is 0.9.13 any chance of 0.9.15 binaries ?

**Comment by jwilk** [comment]
There weren't any changes since 0.9.13 that would affect the Windows build.

Why do you need a new release?

**Comment by GitHubRulesOK** [comment]
agreed on looking through commits since 0.9.13 noe are material comfusion due to web page shuwing latest available as 0.9.15 but download _**appears**_ as if it could be two releases older
