### ISSUE TITLE
Binaries or compilation instructions for MacOS

### ISSUE THREAD

**Issue by aourednik** [jwilk/pdf2djvu#148]
This seems to be the only project still actively promoting the use of DJVU. 
It would be very helpful to have basic compilation instructions.
How can I bring your tool to work on MacOS Monterey? I do have XCode and Homebrew installed. 
Running the following commands:
```
cd path/to/unzipped/folder/from/this/repositoriy/pdf2djvu-master
make
```
Only returns an error:
```
Makefile:15: autoconf.mk: No such file or directory
make: *** No rule to make target `autoconf.mk'.  Stop.
```

**Comment by jwilk** [comment]
> I do have XCode and Homebrew installed. 

`brew install pdf2djvu` should just work (see #147).
