### ISSUE TITLE
Current master requires C++17 to compile

### ISSUE THREAD

**Issue by spaskalev** [jwilk/pdf2djvu#155]
The README states that it needs c++11 but it will fail to compile with it. Adding `-std=c++17 ` to `CXXFLAGS` in autoconf.mk makes it compile successfully.

**Comment by jwilk** [comment]
I believe pdf2djvu proper requires only C++11, as documented.
Some of the required libraries may have stricter requirements, though. For example, recent versions of Poppler (≥ 22, I think) require C++17. This is most likely why you're seeing build errors.

**Comment by spaskalev** [comment]
You are right, the compilation errors are indeed reported for poppler includes. Nevertheless, if works great with C++17 too :) - I've contributed a package for it for Void Linux and it is now available - https://github.com/void-linux/void-packages/commit/40be1cbf1bd62492c36df292bffd172d05fbe2eb

Cheers!
